### ISSUE TITLE
Amazon reload not working

### ISSUE THREAD

**Issue by yashwanth13** [jakehilborn/debbit#77]
I believe amazon might have changed the order of screens/removed some hoops for reloading a giftcard balance. As a result there is no longer a 'Continue' button and directly goes to 'Place your Order' screen. 

Debbit errors out as below:
v2.1.2 Windows Traceback (most recent call last):
  File "debbit.py", line 294, in web_automation_wrapper
  File "C:\Users\Shekhar Alampally\Downloads\debbit-v2.1.2-win64\program_files\merchants\amazon_gift_card_reload.py", line 160, in web_automation
    driver.find_element_by_xpath("//span[contains(text(),'Continue')]").find_element_by_xpath('../..').click()
  File "selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
  File "selenium\webdriver\remote\webdriver.py", line 976, in find_element
  File "selenium\webdriver\remote\webdriver.py", line 321, in execute
  File "selenium\webdriver\remote\errorhandler.py", line 242, in check_response
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //span[contains(text(),'Continue')]

**Comment by jakehilborn** [comment]
Can you try replacing the file program_files\merchants\amazon_gift_card_reload.py with the latest version of that file [here](https://github.com/jakehilborn/debbit/blob/master/src/program_files/merchants/amazon_gift_card_reload.py). I'm pretty sure your issue has been resolved with the latest code.

I've been working on getting a new release out with the latest amazon gift card reload code. Haven't quite finished yet.

**Comment by yashwanth13** [comment]
Jake, it still failed with the latest code. Have a look and test it out when you get a chance. 
Thanks.

**Comment by k10urzd** [comment]
> Can you try replacing the file program_files\merchants\amazon_gift_card_reload.py with the latest version of that file [here](https://github.com/jakehilborn/debbit/blob/master/src/program_files/merchants/amazon_gift_card_reload.py). I'm pretty sure your issue has been resolved with the latest code.
> 
> I've been working on getting a new release out with the latest amazon gift card reload code. Haven't quite finished yet.

I've been checking for the latest release, this code resolved my Amazon problems. Thank you Jake!

**Comment by Tanman897** [comment]
Yeah, I am getting the same error codes and mine did not fix with the updated file as well. Something is still broken.

**Comment by jaj08** [comment]
Just wanted to reply to say that manually updating to your latest file fixed the issues I was having.

**Comment by jakehilborn** [comment]
Debbit [v2.1.3](https://github.com/jakehilborn/debbit/releases/tag/v2.1.3) has been released. I hope this fixes your continue button issue. There have been a few bug fixes so I can't say with 100% certainty. I've enhanced the error reporting emails though so I'll be able to better tell if anything is still broken in v2.1.3.

**Comment by jakehilborn** [comment]
@yashwanth13 @Tanman897 Can you try replacing the file `program_files/merchants/amazon_gift_card_reload.py` with the [lastest version on the master branch](https://github.com/jakehilborn/debbit/blob/master/src/program_files/merchants/amazon_gift_card_reload.py)? I've attempted to fix the `Unable to locate element: //span[contains(text(),'Continue')]` bug but I do not get this workflow on Amazon so I can't verify the fix myself.

**Comment by Tanman897** [comment]
Okay, I have now updated to the latest version and also updated this file like you suggested. Mine is set up to run the 2nd - 12th days of the month for two different cards (15 transactions total). I have already manually processed them since I had not heard back earlier and needed to complete my monthly transactions. I will have to wait till next month to see if it works; fingers crossed! :) Thanks for working on this so promptly!

**Comment by jakehilborn** [comment]
@Tanman897 Another user was able to verify that the `Unable to locate element: //span[contains(text(),'Continue')]` has been fixed. Debbit [v2.1.4](https://github.com/jakehilborn/debbit/releases) includes this bug fix along with some others.

**Comment by yashwanth13** [comment]
I can confirm that the v2.1.4 fixes the issue.
